version: 2.1

orbs:
  webex: webex/teams@dev:alpha

jobs:
  build:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - webex/notify:
          roomID: Y2lzY29zcGFyazovL3VzL1JPT00vYTI2ZWVlMDAtZDVkNS0xMWU5LTkwZDYtN2ZkYjAyZGE4NzI2

workflows:
  your-workflow:
    jobs:
      - build
